spring:
  application:
    name: fishing-copilot

  datasource:
    url: jdbc:postgresql://localhost:5432/fishing-copilot
    username: localLogin
    password: localPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.orm.jpa: DEBUG
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

photo:
  upload-dir: "C:/Users/kira5/OneDrive/Images/copilot-pictures"
